server:
  port: 9191



spring:
  application :
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack

        - id : DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack

#Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#Hystrix Configuration
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
# circuit-breaker - find the services that are not working and will implement fall-back methods
